create table if not exists Person(
	person_id int primary key generated by default as identity,
	first_name varchar(100) not null,
	last_name varchar(100) not null,
	father_name varchar(100) not null,
	phone_number varchar(100),
	username varchar(100) not null unique,
	password varchar(100) not null,
	role varchar(100) not null
);

create table if not exists Event(
	event_id int primary key generated by default as identity,
	person_id int references Person(person_id) on delete cascade,
	name varchar,
	description text,
	start_date date,
	start_time time,
	address varchar,
	is_moderated boolean
);

create table if not exists Photo(
	photo_id int primary key generated by default as identity ,
	event_id int references Event(event_id) on delete cascade,
	file_name varchar,
	path varchar
);

create table if not exists Comment(
	comment_id int primary key generated by default as identity,
	event_id int references Event(event_id) on delete cascade,
	person_id int references Person(person_id) on delete cascade,
	message text,
	date_of_sending date,
	time_of_sending time
	
);

create table if not exists Event_Person(
	event_id int references event(event_id) on delete cascade,
	person_id int references person(person_id) on delete cascade,
	primary key (event_id,person_id)
);
 