create table if not exists Person(
	id int primary key generated by default as identity,
	first_name varchar(100) not null,
	last_name varchar(100) not null,
	father_name varchar(100) not null,
	phone_number varchar(100),
	username varchar(100) not null unique,
	password varchar(100) not null,
	role varchar(100) not null
);


select * from person
 